[package]
name = "chez-ffi"
version = "0.1.0"
authors = ["Akash Shakdwipeea <ashakdwipeea@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"

[lib]
crate-type = ["cdylib"]
